name             'securegit'
maintainer       'TyBrown.NET'
maintainer_email 'admin@tybrown.net'
license          'All rights reserved.'
description      'Provides securegit resource'
long_description 'See README.rst'
version          '0.1.0'
